name: publish book to github pages
on:
  push:
    branches: [ "master" ]
    paths:
      - 'docs/**'
      - 'book.json'
      - 'package.json'
      - 'scripts/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: translate
        uses: chenxizhang/gpt-translator@master
        with:
          openai_api_key: ${{secrets.OPENAI_API_KEY}}
          files: docs/zh/*.md
          to_language: en
          useAzure: true
          endpoint: ${{secrets.OPENAI_API_ENDPOINT_AZURE}}
          rules: |- 
            - You must fully understand the syntex of markdown, you are the expert of markdown.
            - For a markdown link (for example: [link text](././link.md)), the first part is the text, the second part is the link. You don't need to translate the link.
            - For a markdown image (for example: ![image text](././image.png)), the first part is the text, the second part is the link. You don't need to translate the link.
            - If from_language is not English (en, en-us), but you see English text in the file, you should not translate the English text, this might be a keyword or specicial text. FOr example, "这是非官方的 PowerShell SDK, 我的目的是简化大家对于 OpenAI 和 Azure OpenAI 的使用", the from_language is Chinese, but you see "PowerShell SDK", "OpenAI", "Azure OpenAI" in the content, you should not translate them but you need to translate the whole sentence, and use them as keywords.
      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
      
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4