name: publish book to github pages
on:
  push:
    branches: [ "master" ]
    paths:
      - 'docs/**'
      - 'book.json'
      - 'package.json'
      - 'scripts/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: translate
        uses: chenxizhang/gpt-translator@master
        with:
          openai_api_key: ${{secrets.OPENAI_API_KEY}}
          files: docs/zh/*.md
          to_language: en
          useAzure: true
          endpoint: ${{secrets.OPENAI_API_ENDPOINT_AZURE}}
      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
      
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v3